// This file has been generated by Py++.

#ifndef OrbitManipulator_hpp__pyplusplus_wrapper
#define OrbitManipulator_hpp__pyplusplus_wrapper

void register_OrbitManipulator_class();

#endif//OrbitManipulator_hpp__pyplusplus_wrapper
