// This file has been generated by Py++.

#ifndef TrackballManipulator_hpp__pyplusplus_wrapper
#define TrackballManipulator_hpp__pyplusplus_wrapper

void register_TrackballManipulator_class();

#endif//TrackballManipulator_hpp__pyplusplus_wrapper
