// This file has been generated by Py++.

#ifndef DotOsgWrapper_hpp__pyplusplus_wrapper
#define DotOsgWrapper_hpp__pyplusplus_wrapper

void register_DotOsgWrapper_class();

#endif//DotOsgWrapper_hpp__pyplusplus_wrapper
