// This file has been generated by Py++.

#ifndef FindFileCallback_hpp__pyplusplus_wrapper
#define FindFileCallback_hpp__pyplusplus_wrapper

void register_FindFileCallback_class();

#endif//FindFileCallback_hpp__pyplusplus_wrapper
