// This file has been generated by Py++.

#ifndef FinishedObjectReadCallback_hpp__pyplusplus_wrapper
#define FinishedObjectReadCallback_hpp__pyplusplus_wrapper

void register_FinishedObjectReadCallback_class();

#endif//FinishedObjectReadCallback_hpp__pyplusplus_wrapper
