// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_osgdb.h"
#include "objectglenum.pypp.hpp"

namespace bp = boost::python;

void register_ObjectGLenum_class(){

    { //::osgDB::ObjectGLenum
        typedef bp::class_< osgDB::ObjectGLenum > ObjectGLenum_exposer_t;
        ObjectGLenum_exposer_t ObjectGLenum_exposer = ObjectGLenum_exposer_t( "ObjectGLenum", bp::init< bp::optional< GLenum > >(( bp::arg("value")=(::GLenum)(0) )) );
        bp::scope ObjectGLenum_scope( ObjectGLenum_exposer );
        bp::implicitly_convertible< GLenum, osgDB::ObjectGLenum >();
        ObjectGLenum_exposer.def( bp::init< osgDB::ObjectGLenum const & >(( bp::arg("copy") )) );
        { //::osgDB::ObjectGLenum::get
        
            typedef ::GLenum ( ::osgDB::ObjectGLenum::*get_function_type )(  ) const;
            
            ObjectGLenum_exposer.def( 
                "get"
                , get_function_type( &::osgDB::ObjectGLenum::get ) );
        
        }
        { //::osgDB::ObjectGLenum::set
        
            typedef void ( ::osgDB::ObjectGLenum::*set_function_type )( ::GLenum ) ;
            
            ObjectGLenum_exposer.def( 
                "set"
                , set_function_type( &::osgDB::ObjectGLenum::set )
                , ( bp::arg("e") ) );
        
        }
        ObjectGLenum_exposer.def_readwrite( "_value", &osgDB::ObjectGLenum::_value );
    }

}
