// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_osgdb.h"
#include "objectmark.pypp.hpp"

namespace bp = boost::python;

void register_ObjectMark_class(){

    bp::class_< osgDB::ObjectMark >( "ObjectMark", bp::init< >() )    
        .def( bp::init< osgDB::ObjectMark const & >(( bp::arg("copy") )) )    
        .def( 
            "set"
            , (void ( ::osgDB::ObjectMark::* )( char const *,int ))( &::osgDB::ObjectMark::set )
            , ( bp::arg("name"), bp::arg("delta")=(int)(0) ) )    
        .def_readwrite( "_indentDelta", &osgDB::ObjectMark::_indentDelta )    
        .def_readwrite( "_name", &osgDB::ObjectMark::_name );

}
