// This file has been generated by Py++.

#ifndef ReaderWriterInfo_hpp__pyplusplus_wrapper
#define ReaderWriterInfo_hpp__pyplusplus_wrapper

void register_ReaderWriterInfo_class();

#endif//ReaderWriterInfo_hpp__pyplusplus_wrapper
