// This file has been generated by Py++.

#ifndef vector_type_hpp__pyplusplus_wrapper
#define vector_type_hpp__pyplusplus_wrapper

void register_vector_type_class();

#endif//vector_type_hpp__pyplusplus_wrapper
