// This file has been generated by Py++.

#ifndef IsoSurfaceProperty_hpp__pyplusplus_wrapper
#define IsoSurfaceProperty_hpp__pyplusplus_wrapper

void register_IsoSurfaceProperty_class();

#endif//IsoSurfaceProperty_hpp__pyplusplus_wrapper
