// This file has been generated by Py++.

#ifndef Selections_hpp__pyplusplus_wrapper
#define Selections_hpp__pyplusplus_wrapper

void register_Selections_class();

#endif//Selections_hpp__pyplusplus_wrapper
