// This file has been generated by Py++.

#ifndef ModularEmitter_hpp__pyplusplus_wrapper
#define ModularEmitter_hpp__pyplusplus_wrapper

void register_ModularEmitter_class();

#endif//ModularEmitter_hpp__pyplusplus_wrapper
