// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_osgparticle.h"
#include "wrap_referenced.h"
#include "modularemitter.pypp.hpp"

namespace bp = boost::python;

struct ModularEmitter_wrapper : osgParticle::ModularEmitter, bp::wrapper< osgParticle::ModularEmitter > {

    ModularEmitter_wrapper( )
    : osgParticle::ModularEmitter( )
      , bp::wrapper< osgParticle::ModularEmitter >(){
        // null constructor
    
    }

    virtual void accept( ::osg::NodeVisitor & nv ) {
        if( bp::override func_accept = this->get_override( "accept" ) )
            func_accept( boost::ref(nv) );
        else{
            this->osgParticle::ModularEmitter::accept( boost::ref(nv) );
        }
    }
    
    void default_accept( ::osg::NodeVisitor & nv ) {
        osgParticle::ModularEmitter::accept( boost::ref(nv) );
    }

    virtual char const * className(  ) const  {
        if( bp::override func_className = this->get_override( "className" ) )
            return func_className(  );
        else{
            return this->osgParticle::ModularEmitter::className(  );
        }
    }
    
    char const * default_className(  ) const  {
        return osgParticle::ModularEmitter::className( );
    }

    virtual ::osg::Object * clone( ::osg::CopyOp const & copyop ) const  {
        if( bp::override func_clone = this->get_override( "clone" ) )
            return func_clone( boost::ref(copyop) );
        else{
            return this->osgParticle::ModularEmitter::clone( boost::ref(copyop) );
        }
    }
    
    ::osg::Object * default_clone( ::osg::CopyOp const & copyop ) const  {
        return osgParticle::ModularEmitter::clone( boost::ref(copyop) );
    }

    virtual ::osg::Object * cloneType(  ) const  {
        if( bp::override func_cloneType = this->get_override( "cloneType" ) )
            return func_cloneType(  );
        else{
            return this->osgParticle::ModularEmitter::cloneType(  );
        }
    }
    
    ::osg::Object * default_cloneType(  ) const  {
        return osgParticle::ModularEmitter::cloneType( );
    }

    virtual bool isSameKindAs( ::osg::Object const * obj ) const  {
        if( bp::override func_isSameKindAs = this->get_override( "isSameKindAs" ) )
            return func_isSameKindAs( boost::python::ptr(obj) );
        else{
            return this->osgParticle::ModularEmitter::isSameKindAs( boost::python::ptr(obj) );
        }
    }
    
    bool default_isSameKindAs( ::osg::Object const * obj ) const  {
        return osgParticle::ModularEmitter::isSameKindAs( boost::python::ptr(obj) );
    }

    virtual char const * libraryName(  ) const  {
        if( bp::override func_libraryName = this->get_override( "libraryName" ) )
            return func_libraryName(  );
        else{
            return this->osgParticle::ModularEmitter::libraryName(  );
        }
    }
    
    char const * default_libraryName(  ) const  {
        return osgParticle::ModularEmitter::libraryName( );
    }

    virtual ::osg::Camera * asCamera(  ) {
        if( bp::override func_asCamera = this->get_override( "asCamera" ) )
            return func_asCamera(  );
        else{
            return this->osg::Node::asCamera(  );
        }
    }
    
    ::osg::Camera * default_asCamera(  ) {
        return osg::Node::asCamera( );
    }

    virtual ::osg::Camera const * asCamera(  ) const  {
        if( bp::override func_asCamera = this->get_override( "asCamera" ) )
            return func_asCamera(  );
        else{
            return this->osg::Node::asCamera(  );
        }
    }
    
    ::osg::Camera const * default_asCamera(  ) const  {
        return osg::Node::asCamera( );
    }

    virtual ::osg::Geode * asGeode(  ) {
        if( bp::override func_asGeode = this->get_override( "asGeode" ) )
            return func_asGeode(  );
        else{
            return this->osg::Node::asGeode(  );
        }
    }
    
    ::osg::Geode * default_asGeode(  ) {
        return osg::Node::asGeode( );
    }

    virtual ::osg::Geode const * asGeode(  ) const  {
        if( bp::override func_asGeode = this->get_override( "asGeode" ) )
            return func_asGeode(  );
        else{
            return this->osg::Node::asGeode(  );
        }
    }
    
    ::osg::Geode const * default_asGeode(  ) const  {
        return osg::Node::asGeode( );
    }

    virtual ::osg::Group * asGroup(  ) {
        if( bp::override func_asGroup = this->get_override( "asGroup" ) )
            return func_asGroup(  );
        else{
            return this->osg::Node::asGroup(  );
        }
    }
    
    ::osg::Group * default_asGroup(  ) {
        return osg::Node::asGroup( );
    }

    virtual ::osg::Group const * asGroup(  ) const  {
        if( bp::override func_asGroup = this->get_override( "asGroup" ) )
            return func_asGroup(  );
        else{
            return this->osg::Node::asGroup(  );
        }
    }
    
    ::osg::Group const * default_asGroup(  ) const  {
        return osg::Node::asGroup( );
    }

    virtual ::osg::Switch * asSwitch(  ) {
        if( bp::override func_asSwitch = this->get_override( "asSwitch" ) )
            return func_asSwitch(  );
        else{
            return this->osg::Node::asSwitch(  );
        }
    }
    
    ::osg::Switch * default_asSwitch(  ) {
        return osg::Node::asSwitch( );
    }

    virtual ::osg::Switch const * asSwitch(  ) const  {
        if( bp::override func_asSwitch = this->get_override( "asSwitch" ) )
            return func_asSwitch(  );
        else{
            return this->osg::Node::asSwitch(  );
        }
    }
    
    ::osg::Switch const * default_asSwitch(  ) const  {
        return osg::Node::asSwitch( );
    }

    virtual ::osg::Transform * asTransform(  ) {
        if( bp::override func_asTransform = this->get_override( "asTransform" ) )
            return func_asTransform(  );
        else{
            return this->osg::Node::asTransform(  );
        }
    }
    
    ::osg::Transform * default_asTransform(  ) {
        return osg::Node::asTransform( );
    }

    virtual ::osg::Transform const * asTransform(  ) const  {
        if( bp::override func_asTransform = this->get_override( "asTransform" ) )
            return func_asTransform(  );
        else{
            return this->osg::Node::asTransform(  );
        }
    }
    
    ::osg::Transform const * default_asTransform(  ) const  {
        return osg::Node::asTransform( );
    }

    virtual void ascend( ::osg::NodeVisitor & nv ) {
        if( bp::override func_ascend = this->get_override( "ascend" ) )
            func_ascend( boost::ref(nv) );
        else{
            this->osg::Node::ascend( boost::ref(nv) );
        }
    }
    
    void default_ascend( ::osg::NodeVisitor & nv ) {
        osg::Node::ascend( boost::ref(nv) );
    }

    virtual ::osg::BoundingSphere computeBound(  ) const  {
        if( bp::override func_computeBound = this->get_override( "computeBound" ) )
            return func_computeBound(  );
        else{
            return this->osgParticle::ParticleProcessor::computeBound(  );
        }
    }
    
    ::osg::BoundingSphere default_computeBound(  ) const  {
        return osgParticle::ParticleProcessor::computeBound( );
    }

    virtual void computeDataVariance(  ) {
        if( bp::override func_computeDataVariance = this->get_override( "computeDataVariance" ) )
            func_computeDataVariance(  );
        else{
            this->osg::Object::computeDataVariance(  );
        }
    }
    
    void default_computeDataVariance(  ) {
        osg::Object::computeDataVariance( );
    }

    virtual ::osg::Referenced * getUserData(  ) {
        if( bp::override func_getUserData = this->get_override( "getUserData" ) )
            return func_getUserData(  );
        else{
            return this->osg::Object::getUserData(  );
        }
    }
    
    ::osg::Referenced * default_getUserData(  ) {
        return osg::Object::getUserData( );
    }

    virtual ::osg::Referenced const * getUserData(  ) const  {
        if( bp::override func_getUserData = this->get_override( "getUserData" ) )
            return func_getUserData(  );
        else{
            return this->osg::Object::getUserData(  );
        }
    }
    
    ::osg::Referenced const * default_getUserData(  ) const  {
        return osg::Object::getUserData( );
    }

    virtual void resizeGLObjectBuffers( unsigned int arg0 ) {
        if( bp::override func_resizeGLObjectBuffers = this->get_override( "resizeGLObjectBuffers" ) )
            func_resizeGLObjectBuffers( arg0 );
        else{
            this->osg::Node::resizeGLObjectBuffers( arg0 );
        }
    }
    
    void default_resizeGLObjectBuffers( unsigned int arg0 ) {
        osg::Node::resizeGLObjectBuffers( arg0 );
    }

    virtual void setName( ::std::string const & name ) {
        if( bp::override func_setName = this->get_override( "setName" ) )
            func_setName( name );
        else{
            this->osg::Object::setName( name );
        }
    }
    
    void default_setName( ::std::string const & name ) {
        osg::Object::setName( name );
    }

    virtual void setThreadSafeRefUnref( bool threadSafe ) {
        if( bp::override func_setThreadSafeRefUnref = this->get_override( "setThreadSafeRefUnref" ) )
            func_setThreadSafeRefUnref( threadSafe );
        else{
            this->osg::Node::setThreadSafeRefUnref( threadSafe );
        }
    }
    
    void default_setThreadSafeRefUnref( bool threadSafe ) {
        osg::Node::setThreadSafeRefUnref( threadSafe );
    }

    virtual void setUserData( ::osg::Referenced * obj ) {
        if( bp::override func_setUserData = this->get_override( "setUserData" ) )
            func_setUserData( boost::python::ptr(obj) );
        else{
            this->osg::Object::setUserData( boost::python::ptr(obj) );
        }
    }
    
    void default_setUserData( ::osg::Referenced * obj ) {
        osg::Object::setUserData( boost::python::ptr(obj) );
    }

    virtual void traverse( ::osg::NodeVisitor & nv ) {
        if( bp::override func_traverse = this->get_override( "traverse" ) )
            func_traverse( boost::ref(nv) );
        else{
            this->osgParticle::ParticleProcessor::traverse( boost::ref(nv) );
        }
    }
    
    void default_traverse( ::osg::NodeVisitor & nv ) {
        osgParticle::ParticleProcessor::traverse( boost::ref(nv) );
    }

};

void register_ModularEmitter_class(){

    bp::class_< ModularEmitter_wrapper, bp::bases< osgParticle::Emitter >, osg::ref_ptr< ModularEmitter_wrapper >, boost::noncopyable >( "ModularEmitter", "\n    An emitter class that holds three objects to control the creation of particles.\n        These objects are a <I>counter</I>, a <I>placer</I> and a <I>shooter</I>.\n        The counter controls the number of particles to be emitted at each frame;\n        the placer must initialize the particles position vector, while the shooter initializes\n        its velocity vector.\n        You can use the predefined counter/placer/shooter classes, or you can create your own.\n", bp::no_init )    
        .def( bp::init< >("\n    An emitter class that holds three objects to control the creation of particles.\n        These objects are a <I>counter</I>, a <I>placer</I> and a <I>shooter</I>.\n        The counter controls the number of particles to be emitted at each frame;\n        the placer must initialize the particles position vector, while the shooter initializes\n        its velocity vector.\n        You can use the predefined counter/placer/shooter classes, or you can create your own.\n") )    
        .def( 
            "accept"
            , (void ( ::osgParticle::ModularEmitter::* )( ::osg::NodeVisitor & ))(&::osgParticle::ModularEmitter::accept)
            , (void ( ModularEmitter_wrapper::* )( ::osg::NodeVisitor & ))(&ModularEmitter_wrapper::default_accept)
            , ( bp::arg("nv") ) )    
        .def( 
            "className"
            , (char const * ( ::osgParticle::ModularEmitter::* )(  )const)(&::osgParticle::ModularEmitter::className)
            , (char const * ( ModularEmitter_wrapper::* )(  )const)(&ModularEmitter_wrapper::default_className) )    
        .def( 
            "clone"
            , (::osg::Object * ( ::osgParticle::ModularEmitter::* )( ::osg::CopyOp const & )const)(&::osgParticle::ModularEmitter::clone)
            , (::osg::Object * ( ModularEmitter_wrapper::* )( ::osg::CopyOp const & )const)(&ModularEmitter_wrapper::default_clone)
            , ( bp::arg("copyop") )
            , bp::return_value_policy< bp::reference_existing_object >() )    
        .def( 
            "cloneType"
            , (::osg::Object * ( ::osgParticle::ModularEmitter::* )(  )const)(&::osgParticle::ModularEmitter::cloneType)
            , (::osg::Object * ( ModularEmitter_wrapper::* )(  )const)(&ModularEmitter_wrapper::default_cloneType)
            , bp::return_value_policy< bp::reference_existing_object >() )    
        .def( 
            "getCounter"
            , (::osgParticle::Counter * ( ::osgParticle::ModularEmitter::* )(  ))( &::osgParticle::ModularEmitter::getCounter )
            , bp::return_internal_reference< >() )    
        .def( 
            "getCounter"
            , (::osgParticle::Counter const * ( ::osgParticle::ModularEmitter::* )(  )const)( &::osgParticle::ModularEmitter::getCounter )
            , bp::return_internal_reference< >() )    
        .def( 
            "getNumParticlesToCreateMovementCompensationRatio"
            , (float ( ::osgParticle::ModularEmitter::* )(  )const)( &::osgParticle::ModularEmitter::getNumParticlesToCreateMovementCompensationRatio ) )    
        .def( 
            "getPlacer"
            , (::osgParticle::Placer * ( ::osgParticle::ModularEmitter::* )(  ))( &::osgParticle::ModularEmitter::getPlacer )
            , bp::return_internal_reference< >() )    
        .def( 
            "getPlacer"
            , (::osgParticle::Placer const * ( ::osgParticle::ModularEmitter::* )(  )const)( &::osgParticle::ModularEmitter::getPlacer )
            , bp::return_internal_reference< >() )    
        .def( 
            "getShooter"
            , (::osgParticle::Shooter * ( ::osgParticle::ModularEmitter::* )(  ))( &::osgParticle::ModularEmitter::getShooter )
            , bp::return_internal_reference< >() )    
        .def( 
            "getShooter"
            , (::osgParticle::Shooter const * ( ::osgParticle::ModularEmitter::* )(  )const)( &::osgParticle::ModularEmitter::getShooter )
            , bp::return_internal_reference< >() )    
        .def( 
            "isSameKindAs"
            , (bool ( ::osgParticle::ModularEmitter::* )( ::osg::Object const * )const)(&::osgParticle::ModularEmitter::isSameKindAs)
            , (bool ( ModularEmitter_wrapper::* )( ::osg::Object const * )const)(&ModularEmitter_wrapper::default_isSameKindAs)
            , ( bp::arg("obj") ) )    
        .def( 
            "libraryName"
            , (char const * ( ::osgParticle::ModularEmitter::* )(  )const)(&::osgParticle::ModularEmitter::libraryName)
            , (char const * ( ModularEmitter_wrapper::* )(  )const)(&ModularEmitter_wrapper::default_libraryName) )    
        .def( 
            "setCounter"
            , (void ( ::osgParticle::ModularEmitter::* )( ::osgParticle::Counter * ))( &::osgParticle::ModularEmitter::setCounter )
            , ( bp::arg("c") ) )    
        .def( 
            "setNumParticlesToCreateMovementCompensationRatio"
            , (void ( ::osgParticle::ModularEmitter::* )( float ))( &::osgParticle::ModularEmitter::setNumParticlesToCreateMovementCompensationRatio )
            , ( bp::arg("r") ) )    
        .def( 
            "setPlacer"
            , (void ( ::osgParticle::ModularEmitter::* )( ::osgParticle::Placer * ))( &::osgParticle::ModularEmitter::setPlacer )
            , ( bp::arg("p") ) )    
        .def( 
            "setShooter"
            , (void ( ::osgParticle::ModularEmitter::* )( ::osgParticle::Shooter * ))( &::osgParticle::ModularEmitter::setShooter )
            , ( bp::arg("s") ) )    
        .def( 
            "computeBound"
            , (::osg::BoundingSphere ( ::osgParticle::ParticleProcessor::* )(  )const)(&::osgParticle::ParticleProcessor::computeBound)
            , (::osg::BoundingSphere ( ModularEmitter_wrapper::* )(  )const)(&ModularEmitter_wrapper::default_computeBound) )    
        .def( 
            "traverse"
            , (void ( ::osgParticle::ParticleProcessor::* )( ::osg::NodeVisitor & ))(&::osgParticle::ParticleProcessor::traverse)
            , (void ( ModularEmitter_wrapper::* )( ::osg::NodeVisitor & ))(&ModularEmitter_wrapper::default_traverse)
            , ( bp::arg("nv") ) );

}
