// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_osganimation.h"
#include "inoutcircfunction.pypp.hpp"

namespace bp = boost::python;

void register_InOutCircFunction_class(){

    bp::class_< osgAnimation::InOutCircFunction >( "InOutCircFunction" )    
        .def( 
            "getValueAt"
            , (void (*)( float,float & ))( &::osgAnimation::InOutCircFunction::getValueAt )
            , ( bp::arg("t"), bp::arg("result") ) )    
        .staticmethod( "getValueAt" );

}
