// This file has been generated by Py++.

#ifndef LinkVisitor_hpp__pyplusplus_wrapper
#define LinkVisitor_hpp__pyplusplus_wrapper

void register_LinkVisitor_class();

#endif//LinkVisitor_hpp__pyplusplus_wrapper
