// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_osganimation.h"
#include "wrap_referenced.h"
#include "stackedmatrixelement.pypp.hpp"

namespace bp = boost::python;

struct StackedMatrixElement_wrapper : osgAnimation::StackedMatrixElement, bp::wrapper< osgAnimation::StackedMatrixElement > {

    StackedMatrixElement_wrapper( )
    : osgAnimation::StackedMatrixElement( )
      , bp::wrapper< osgAnimation::StackedMatrixElement >(){
        // null constructor
    
    }

    StackedMatrixElement_wrapper(::std::string const & name, ::osg::Matrix const & matrix )
    : osgAnimation::StackedMatrixElement( name, boost::ref(matrix) )
      , bp::wrapper< osgAnimation::StackedMatrixElement >(){
        // constructor
    
    }

    StackedMatrixElement_wrapper(::osg::Matrix const & matrix )
    : osgAnimation::StackedMatrixElement( boost::ref(matrix) )
      , bp::wrapper< osgAnimation::StackedMatrixElement >(){
        // constructor
    
    }

    virtual void applyToMatrix( ::osg::Matrix & matrix ) const  {
        if( bp::override func_applyToMatrix = this->get_override( "applyToMatrix" ) )
            func_applyToMatrix( boost::ref(matrix) );
        else{
            this->osgAnimation::StackedMatrixElement::applyToMatrix( boost::ref(matrix) );
        }
    }
    
    void default_applyToMatrix( ::osg::Matrix & matrix ) const  {
        osgAnimation::StackedMatrixElement::applyToMatrix( boost::ref(matrix) );
    }

    virtual char const * className(  ) const  {
        if( bp::override func_className = this->get_override( "className" ) )
            return func_className(  );
        else{
            return this->osgAnimation::StackedMatrixElement::className(  );
        }
    }
    
    char const * default_className(  ) const  {
        return osgAnimation::StackedMatrixElement::className( );
    }

    virtual ::osg::Object * clone( ::osg::CopyOp const & copyop ) const  {
        if( bp::override func_clone = this->get_override( "clone" ) )
            return func_clone( boost::ref(copyop) );
        else{
            return this->osgAnimation::StackedMatrixElement::clone( boost::ref(copyop) );
        }
    }
    
    ::osg::Object * default_clone( ::osg::CopyOp const & copyop ) const  {
        return osgAnimation::StackedMatrixElement::clone( boost::ref(copyop) );
    }

    virtual ::osg::Object * cloneType(  ) const  {
        if( bp::override func_cloneType = this->get_override( "cloneType" ) )
            return func_cloneType(  );
        else{
            return this->osgAnimation::StackedMatrixElement::cloneType(  );
        }
    }
    
    ::osg::Object * default_cloneType(  ) const  {
        return osgAnimation::StackedMatrixElement::cloneType( );
    }

    virtual ::osg::Matrix getAsMatrix(  ) const  {
        if( bp::override func_getAsMatrix = this->get_override( "getAsMatrix" ) )
            return func_getAsMatrix(  );
        else{
            return this->osgAnimation::StackedMatrixElement::getAsMatrix(  );
        }
    }
    
    ::osg::Matrix default_getAsMatrix(  ) const  {
        return osgAnimation::StackedMatrixElement::getAsMatrix( );
    }

    virtual ::osgAnimation::Target * getOrCreateTarget(  ) {
        if( bp::override func_getOrCreateTarget = this->get_override( "getOrCreateTarget" ) )
            return func_getOrCreateTarget(  );
        else{
            return this->osgAnimation::StackedMatrixElement::getOrCreateTarget(  );
        }
    }
    
    ::osgAnimation::Target * default_getOrCreateTarget(  ) {
        return osgAnimation::StackedMatrixElement::getOrCreateTarget( );
    }

    virtual ::osgAnimation::Target * getTarget(  ) {
        if( bp::override func_getTarget = this->get_override( "getTarget" ) )
            return func_getTarget(  );
        else{
            return this->osgAnimation::StackedMatrixElement::getTarget(  );
        }
    }
    
    ::osgAnimation::Target * default_getTarget(  ) {
        return osgAnimation::StackedMatrixElement::getTarget( );
    }

    virtual ::osgAnimation::Target const * getTarget(  ) const  {
        if( bp::override func_getTarget = this->get_override( "getTarget" ) )
            return func_getTarget(  );
        else{
            return this->osgAnimation::StackedMatrixElement::getTarget(  );
        }
    }
    
    ::osgAnimation::Target const * default_getTarget(  ) const  {
        return osgAnimation::StackedMatrixElement::getTarget( );
    }

    virtual bool isIdentity(  ) const  {
        if( bp::override func_isIdentity = this->get_override( "isIdentity" ) )
            return func_isIdentity(  );
        else{
            return this->osgAnimation::StackedMatrixElement::isIdentity(  );
        }
    }
    
    bool default_isIdentity(  ) const  {
        return osgAnimation::StackedMatrixElement::isIdentity( );
    }

    virtual bool isSameKindAs( ::osg::Object const * obj ) const  {
        if( bp::override func_isSameKindAs = this->get_override( "isSameKindAs" ) )
            return func_isSameKindAs( boost::python::ptr(obj) );
        else{
            return this->osgAnimation::StackedMatrixElement::isSameKindAs( boost::python::ptr(obj) );
        }
    }
    
    bool default_isSameKindAs( ::osg::Object const * obj ) const  {
        return osgAnimation::StackedMatrixElement::isSameKindAs( boost::python::ptr(obj) );
    }

    virtual char const * libraryName(  ) const  {
        if( bp::override func_libraryName = this->get_override( "libraryName" ) )
            return func_libraryName(  );
        else{
            return this->osgAnimation::StackedMatrixElement::libraryName(  );
        }
    }
    
    char const * default_libraryName(  ) const  {
        return osgAnimation::StackedMatrixElement::libraryName( );
    }

    virtual void update( float t=0.0 ) {
        if( bp::override func_update = this->get_override( "update" ) )
            func_update( t );
        else{
            this->osgAnimation::StackedMatrixElement::update( t );
        }
    }
    
    void default_update( float t=0.0 ) {
        osgAnimation::StackedMatrixElement::update( t );
    }

    virtual void computeDataVariance(  ) {
        if( bp::override func_computeDataVariance = this->get_override( "computeDataVariance" ) )
            func_computeDataVariance(  );
        else{
            this->osg::Object::computeDataVariance(  );
        }
    }
    
    void default_computeDataVariance(  ) {
        osg::Object::computeDataVariance( );
    }

    virtual ::osg::Referenced * getUserData(  ) {
        if( bp::override func_getUserData = this->get_override( "getUserData" ) )
            return func_getUserData(  );
        else{
            return this->osg::Object::getUserData(  );
        }
    }
    
    ::osg::Referenced * default_getUserData(  ) {
        return osg::Object::getUserData( );
    }

    virtual ::osg::Referenced const * getUserData(  ) const  {
        if( bp::override func_getUserData = this->get_override( "getUserData" ) )
            return func_getUserData(  );
        else{
            return this->osg::Object::getUserData(  );
        }
    }
    
    ::osg::Referenced const * default_getUserData(  ) const  {
        return osg::Object::getUserData( );
    }

    virtual void resizeGLObjectBuffers( unsigned int arg0 ) {
        if( bp::override func_resizeGLObjectBuffers = this->get_override( "resizeGLObjectBuffers" ) )
            func_resizeGLObjectBuffers( arg0 );
        else{
            this->osg::Object::resizeGLObjectBuffers( arg0 );
        }
    }
    
    void default_resizeGLObjectBuffers( unsigned int arg0 ) {
        osg::Object::resizeGLObjectBuffers( arg0 );
    }

    virtual void setName( ::std::string const & name ) {
        if( bp::override func_setName = this->get_override( "setName" ) )
            func_setName( name );
        else{
            this->osg::Object::setName( name );
        }
    }
    
    void default_setName( ::std::string const & name ) {
        osg::Object::setName( name );
    }

    virtual void setThreadSafeRefUnref( bool threadSafe ) {
        if( bp::override func_setThreadSafeRefUnref = this->get_override( "setThreadSafeRefUnref" ) )
            func_setThreadSafeRefUnref( threadSafe );
        else{
            this->osg::Object::setThreadSafeRefUnref( threadSafe );
        }
    }
    
    void default_setThreadSafeRefUnref( bool threadSafe ) {
        osg::Object::setThreadSafeRefUnref( threadSafe );
    }

    virtual void setUserData( ::osg::Referenced * obj ) {
        if( bp::override func_setUserData = this->get_override( "setUserData" ) )
            func_setUserData( boost::python::ptr(obj) );
        else{
            this->osg::Object::setUserData( boost::python::ptr(obj) );
        }
    }
    
    void default_setUserData( ::osg::Referenced * obj ) {
        osg::Object::setUserData( boost::python::ptr(obj) );
    }

};

void register_StackedMatrixElement_class(){

    { //::osgAnimation::StackedMatrixElement
        typedef bp::class_< StackedMatrixElement_wrapper, bp::bases< osgAnimation::StackedTransformElement >, osg::ref_ptr< StackedMatrixElement_wrapper >, boost::noncopyable > StackedMatrixElement_exposer_t;
        StackedMatrixElement_exposer_t StackedMatrixElement_exposer = StackedMatrixElement_exposer_t( "StackedMatrixElement", bp::init< >() );
        bp::scope StackedMatrixElement_scope( StackedMatrixElement_exposer );
        StackedMatrixElement_exposer.def( bp::init< std::string const &, osg::Matrix const & >(( bp::arg("name"), bp::arg("matrix") )) );
        StackedMatrixElement_exposer.def( bp::init< osg::Matrix const & >(( bp::arg("matrix") )) );
        bp::implicitly_convertible< osg::Matrix const &, osgAnimation::StackedMatrixElement >();
        { //::osgAnimation::StackedMatrixElement::applyToMatrix
        
            typedef void ( ::osgAnimation::StackedMatrixElement::*applyToMatrix_function_type)( ::osg::Matrix & ) const;
            typedef void ( StackedMatrixElement_wrapper::*default_applyToMatrix_function_type)( ::osg::Matrix & ) const;
            
            StackedMatrixElement_exposer.def( 
                "applyToMatrix"
                , applyToMatrix_function_type(&::osgAnimation::StackedMatrixElement::applyToMatrix)
                , default_applyToMatrix_function_type(&StackedMatrixElement_wrapper::default_applyToMatrix)
                , ( bp::arg("matrix") ) );
        
        }
        { //::osgAnimation::StackedMatrixElement::className
        
            typedef char const * ( ::osgAnimation::StackedMatrixElement::*className_function_type)(  ) const;
            typedef char const * ( StackedMatrixElement_wrapper::*default_className_function_type)(  ) const;
            
            StackedMatrixElement_exposer.def( 
                "className"
                , className_function_type(&::osgAnimation::StackedMatrixElement::className)
                , default_className_function_type(&StackedMatrixElement_wrapper::default_className) );
        
        }
        { //::osgAnimation::StackedMatrixElement::clone
        
            typedef ::osg::Object * ( ::osgAnimation::StackedMatrixElement::*clone_function_type)( ::osg::CopyOp const & ) const;
            typedef ::osg::Object * ( StackedMatrixElement_wrapper::*default_clone_function_type)( ::osg::CopyOp const & ) const;
            
            StackedMatrixElement_exposer.def( 
                "clone"
                , clone_function_type(&::osgAnimation::StackedMatrixElement::clone)
                , default_clone_function_type(&StackedMatrixElement_wrapper::default_clone)
                , ( bp::arg("copyop") )
                , bp::return_value_policy< bp::reference_existing_object >() );
        
        }
        { //::osgAnimation::StackedMatrixElement::cloneType
        
            typedef ::osg::Object * ( ::osgAnimation::StackedMatrixElement::*cloneType_function_type)(  ) const;
            typedef ::osg::Object * ( StackedMatrixElement_wrapper::*default_cloneType_function_type)(  ) const;
            
            StackedMatrixElement_exposer.def( 
                "cloneType"
                , cloneType_function_type(&::osgAnimation::StackedMatrixElement::cloneType)
                , default_cloneType_function_type(&StackedMatrixElement_wrapper::default_cloneType)
                , bp::return_value_policy< bp::reference_existing_object >() );
        
        }
        { //::osgAnimation::StackedMatrixElement::getAsMatrix
        
            typedef ::osg::Matrix ( ::osgAnimation::StackedMatrixElement::*getAsMatrix_function_type)(  ) const;
            typedef ::osg::Matrix ( StackedMatrixElement_wrapper::*default_getAsMatrix_function_type)(  ) const;
            
            StackedMatrixElement_exposer.def( 
                "getAsMatrix"
                , getAsMatrix_function_type(&::osgAnimation::StackedMatrixElement::getAsMatrix)
                , default_getAsMatrix_function_type(&StackedMatrixElement_wrapper::default_getAsMatrix) );
        
        }
        { //::osgAnimation::StackedMatrixElement::getMatrix
        
            typedef ::osg::Matrix const & ( ::osgAnimation::StackedMatrixElement::*getMatrix_function_type)(  ) const;
            
            StackedMatrixElement_exposer.def( 
                "getMatrix"
                , getMatrix_function_type( &::osgAnimation::StackedMatrixElement::getMatrix )
                , bp::return_internal_reference< >() );
        
        }
        { //::osgAnimation::StackedMatrixElement::getOrCreateTarget
        
            typedef ::osgAnimation::Target * ( ::osgAnimation::StackedMatrixElement::*getOrCreateTarget_function_type)(  ) ;
            typedef ::osgAnimation::Target * ( StackedMatrixElement_wrapper::*default_getOrCreateTarget_function_type)(  ) ;
            
            StackedMatrixElement_exposer.def( 
                "getOrCreateTarget"
                , getOrCreateTarget_function_type(&::osgAnimation::StackedMatrixElement::getOrCreateTarget)
                , default_getOrCreateTarget_function_type(&StackedMatrixElement_wrapper::default_getOrCreateTarget)
                , bp::return_internal_reference< >() );
        
        }
        { //::osgAnimation::StackedMatrixElement::getTarget
        
            typedef ::osgAnimation::Target * ( ::osgAnimation::StackedMatrixElement::*getTarget_function_type)(  ) ;
            typedef ::osgAnimation::Target * ( StackedMatrixElement_wrapper::*default_getTarget_function_type)(  ) ;
            
            StackedMatrixElement_exposer.def( 
                "getTarget"
                , getTarget_function_type(&::osgAnimation::StackedMatrixElement::getTarget)
                , default_getTarget_function_type(&StackedMatrixElement_wrapper::default_getTarget)
                , bp::return_internal_reference< >() );
        
        }
        { //::osgAnimation::StackedMatrixElement::getTarget
        
            typedef ::osgAnimation::Target const * ( ::osgAnimation::StackedMatrixElement::*getTarget_function_type)(  ) const;
            typedef ::osgAnimation::Target const * ( StackedMatrixElement_wrapper::*default_getTarget_function_type)(  ) const;
            
            StackedMatrixElement_exposer.def( 
                "getTarget"
                , getTarget_function_type(&::osgAnimation::StackedMatrixElement::getTarget)
                , default_getTarget_function_type(&StackedMatrixElement_wrapper::default_getTarget)
                , bp::return_internal_reference< >() );
        
        }
        { //::osgAnimation::StackedMatrixElement::isIdentity
        
            typedef bool ( ::osgAnimation::StackedMatrixElement::*isIdentity_function_type)(  ) const;
            typedef bool ( StackedMatrixElement_wrapper::*default_isIdentity_function_type)(  ) const;
            
            StackedMatrixElement_exposer.def( 
                "isIdentity"
                , isIdentity_function_type(&::osgAnimation::StackedMatrixElement::isIdentity)
                , default_isIdentity_function_type(&StackedMatrixElement_wrapper::default_isIdentity) );
        
        }
        { //::osgAnimation::StackedMatrixElement::isSameKindAs
        
            typedef bool ( ::osgAnimation::StackedMatrixElement::*isSameKindAs_function_type)( ::osg::Object const * ) const;
            typedef bool ( StackedMatrixElement_wrapper::*default_isSameKindAs_function_type)( ::osg::Object const * ) const;
            
            StackedMatrixElement_exposer.def( 
                "isSameKindAs"
                , isSameKindAs_function_type(&::osgAnimation::StackedMatrixElement::isSameKindAs)
                , default_isSameKindAs_function_type(&StackedMatrixElement_wrapper::default_isSameKindAs)
                , ( bp::arg("obj") ) );
        
        }
        { //::osgAnimation::StackedMatrixElement::libraryName
        
            typedef char const * ( ::osgAnimation::StackedMatrixElement::*libraryName_function_type)(  ) const;
            typedef char const * ( StackedMatrixElement_wrapper::*default_libraryName_function_type)(  ) const;
            
            StackedMatrixElement_exposer.def( 
                "libraryName"
                , libraryName_function_type(&::osgAnimation::StackedMatrixElement::libraryName)
                , default_libraryName_function_type(&StackedMatrixElement_wrapper::default_libraryName) );
        
        }
        { //::osgAnimation::StackedMatrixElement::setMatrix
        
            typedef void ( ::osgAnimation::StackedMatrixElement::*setMatrix_function_type)( ::osg::Matrix const & ) ;
            
            StackedMatrixElement_exposer.def( 
                "setMatrix"
                , setMatrix_function_type( &::osgAnimation::StackedMatrixElement::setMatrix )
                , ( bp::arg("matrix") ) );
        
        }
        { //::osgAnimation::StackedMatrixElement::update
        
            typedef void ( ::osgAnimation::StackedMatrixElement::*update_function_type)( float ) ;
            typedef void ( StackedMatrixElement_wrapper::*default_update_function_type)( float ) ;
            
            StackedMatrixElement_exposer.def( 
                "update"
                , update_function_type(&::osgAnimation::StackedMatrixElement::update)
                , default_update_function_type(&StackedMatrixElement_wrapper::default_update)
                , ( bp::arg("t")=0.0 ) );
        
        }
    }

}
