// This file has been generated by Py++.

#ifndef AddRangeOperator_hpp__pyplusplus_wrapper
#define AddRangeOperator_hpp__pyplusplus_wrapper

void register_AddRangeOperator_class();

#endif//AddRangeOperator_hpp__pyplusplus_wrapper
