// This file has been generated by Py++.

#ifndef PlaneIntersections_hpp__pyplusplus_wrapper
#define PlaneIntersections_hpp__pyplusplus_wrapper

void register_PlaneIntersections_class();

#endif//PlaneIntersections_hpp__pyplusplus_wrapper
