// This file has been generated by Py++.

#ifndef PrimitiveValueMap_hpp__pyplusplus_wrapper
#define PrimitiveValueMap_hpp__pyplusplus_wrapper

void register_PrimitiveValueMap_class();

#endif//PrimitiveValueMap_hpp__pyplusplus_wrapper
