// This file has been generated by Py++.

#ifndef RenderBinList_hpp__pyplusplus_wrapper
#define RenderBinList_hpp__pyplusplus_wrapper

void register_RenderBinList_class();

#endif//RenderBinList_hpp__pyplusplus_wrapper
