// This file has been generated by Py++.

#include "boost/python.hpp"
#include "boost/python/suite/indexing/vector_indexing_suite.hpp"
#include "wrap_osgutil.h"
#include "vector_less__osgutil_scope_stategraph_ptr___greater_.pypp.hpp"

namespace bp = boost::python;

void register_vector_less__osgUtil_scope_StateGraph_ptr___greater__class(){

    { //::std::vector< osgUtil::StateGraph* >
        typedef bp::class_< std::vector< osgUtil::StateGraph* > > vector_less__osgUtil_scope_StateGraph_ptr___greater__exposer_t;
        vector_less__osgUtil_scope_StateGraph_ptr___greater__exposer_t vector_less__osgUtil_scope_StateGraph_ptr___greater__exposer = vector_less__osgUtil_scope_StateGraph_ptr___greater__exposer_t( "vector_less__osgUtil_scope_StateGraph_ptr___greater_" );
        bp::scope vector_less__osgUtil_scope_StateGraph_ptr___greater__scope( vector_less__osgUtil_scope_StateGraph_ptr___greater__exposer );
        vector_less__osgUtil_scope_StateGraph_ptr___greater__exposer.def( bp::vector_indexing_suite< ::std::vector< osgUtil::StateGraph* > >() );
    }

}
