// This file has been generated by Py++.

#include "boost/python.hpp"
#include "indexing_suite/container_suite.hpp"
#include "indexing_suite/map.hpp"
#include "wrap_osg.h"
#include "_ActiveVarInfo__value_traits.pypp.hpp"
#include "activevarinfomap.pypp.hpp"

namespace bp = boost::python;

void register_ActiveVarInfoMap_class(){

    bp::class_< std::map< std::string, osg::Program::ActiveVarInfo > >( "ActiveVarInfoMap" )    
        .def( bp::indexing::map_suite< std::map< std::string, osg::Program::ActiveVarInfo > >() );

}
