// This file has been generated by Py++.

#ifndef ArgumentParser_hpp__pyplusplus_wrapper
#define ArgumentParser_hpp__pyplusplus_wrapper

void register_ArgumentParser_class();

#endif//ArgumentParser_hpp__pyplusplus_wrapper
