// This file has been generated by Py++.

#ifndef ClipPlane_hpp__pyplusplus_wrapper
#define ClipPlane_hpp__pyplusplus_wrapper

void register_ClipPlane_class();

#endif//ClipPlane_hpp__pyplusplus_wrapper
