// This file has been generated by Py++.

#ifndef ClipPlaneList_hpp__pyplusplus_wrapper
#define ClipPlaneList_hpp__pyplusplus_wrapper

void register_ClipPlaneList_class();

#endif//ClipPlaneList_hpp__pyplusplus_wrapper
