// This file has been generated by Py++.

#ifndef GLBufferObjects_hpp__pyplusplus_wrapper
#define GLBufferObjects_hpp__pyplusplus_wrapper

void register_GLBufferObjects_class();

#endif//GLBufferObjects_hpp__pyplusplus_wrapper
