// This file has been generated by Py++.

#ifndef ObserverNodePath_hpp__pyplusplus_wrapper
#define ObserverNodePath_hpp__pyplusplus_wrapper

void register_ObserverNodePath_class();

#endif//ObserverNodePath_hpp__pyplusplus_wrapper
