// This file has been generated by Py++.

#ifndef PointSprite_hpp__pyplusplus_wrapper
#define PointSprite_hpp__pyplusplus_wrapper

void register_PointSprite_class();

#endif//PointSprite_hpp__pyplusplus_wrapper
