// This file has been generated by Py++.

#ifndef RenderInfo_hpp__pyplusplus_wrapper
#define RenderInfo_hpp__pyplusplus_wrapper

void register_RenderInfo_class();

#endif//RenderInfo_hpp__pyplusplus_wrapper
