// This file has been generated by Py++.

#ifndef TextureCubeMap_hpp__pyplusplus_wrapper
#define TextureCubeMap_hpp__pyplusplus_wrapper

void register_TextureCubeMap_class();

#endif//TextureCubeMap_hpp__pyplusplus_wrapper
