// This file has been generated by Py++.

#include "boost/python.hpp"
#include "boost/python/suite/indexing/vector_indexing_suite.hpp"
#include "wrap_osg.h"
#include "vertexattribaliaslist.pypp.hpp"

namespace bp = boost::python;

void register_VertexAttribAliasList_class(){

    { //::std::vector< osg::VertexAttribAlias >
        typedef bp::class_< std::vector< osg::VertexAttribAlias > > VertexAttribAliasList_exposer_t;
        VertexAttribAliasList_exposer_t VertexAttribAliasList_exposer = VertexAttribAliasList_exposer_t( "VertexAttribAliasList" );
        bp::scope VertexAttribAliasList_scope( VertexAttribAliasList_exposer );
        //WARNING: the next line of code will not compile, because "::osg::VertexAttribAlias" does not have operator== !
        VertexAttribAliasList_exposer.def( bp::vector_indexing_suite< ::std::vector< osg::VertexAttribAlias > >() );
    }

}
