// This file has been generated by Py++.

#ifndef GlyphTextureList_hpp__pyplusplus_wrapper
#define GlyphTextureList_hpp__pyplusplus_wrapper

void register_GlyphTextureList_class();

#endif//GlyphTextureList_hpp__pyplusplus_wrapper
