// This file has been generated by Py++.

#ifndef VectorUInt_hpp__pyplusplus_wrapper
#define VectorUInt_hpp__pyplusplus_wrapper

void register_VectorUInt_class();

#endif//VectorUInt_hpp__pyplusplus_wrapper
