// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_osgwidget.h"
#include "_osgwidget_global_variables.pypp.hpp"

namespace bp = boost::python;

void register_global_variables(){

    bp::scope().attr("DESCENT_STRING") = osgWidget::DESCENT_STRING;

    bp::scope().attr("OSGWIDGET_RENDERBIN_MOD") = osgWidget::OSGWIDGET_RENDERBIN_MOD;

}
