// This file has been generated by Py++.

#ifndef ViewConfig_hpp__pyplusplus_wrapper
#define ViewConfig_hpp__pyplusplus_wrapper

void register_ViewConfig_class();

#endif//ViewConfig_hpp__pyplusplus_wrapper
