// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_osgsim.h"
#include "wrap_referenced.h"
#include "multiswitch.pypp.hpp"

namespace bp = boost::python;

struct MultiSwitch_wrapper : osgSim::MultiSwitch, bp::wrapper< osgSim::MultiSwitch > {

    MultiSwitch_wrapper( )
    : osgSim::MultiSwitch( )
      , bp::wrapper< osgSim::MultiSwitch >(){
        // null constructor
    
    }

    virtual void accept( ::osg::NodeVisitor & nv ) {
        if( bp::override func_accept = this->get_override( "accept" ) )
            func_accept( boost::ref(nv) );
        else{
            this->osgSim::MultiSwitch::accept( boost::ref(nv) );
        }
    }
    
    void default_accept( ::osg::NodeVisitor & nv ) {
        osgSim::MultiSwitch::accept( boost::ref(nv) );
    }

    virtual bool addChild( ::osg::Node * child ) {
        if( bp::override func_addChild = this->get_override( "addChild" ) )
            return func_addChild( boost::python::ptr(child) );
        else{
            return this->osgSim::MultiSwitch::addChild( boost::python::ptr(child) );
        }
    }
    
    bool default_addChild( ::osg::Node * child ) {
        return osgSim::MultiSwitch::addChild( boost::python::ptr(child) );
    }

    virtual char const * className(  ) const  {
        if( bp::override func_className = this->get_override( "className" ) )
            return func_className(  );
        else{
            return this->osgSim::MultiSwitch::className(  );
        }
    }
    
    char const * default_className(  ) const  {
        return osgSim::MultiSwitch::className( );
    }

    virtual ::osg::Object * clone( ::osg::CopyOp const & copyop ) const  {
        if( bp::override func_clone = this->get_override( "clone" ) )
            return func_clone( boost::ref(copyop) );
        else{
            return this->osgSim::MultiSwitch::clone( boost::ref(copyop) );
        }
    }
    
    ::osg::Object * default_clone( ::osg::CopyOp const & copyop ) const  {
        return osgSim::MultiSwitch::clone( boost::ref(copyop) );
    }

    virtual ::osg::Object * cloneType(  ) const  {
        if( bp::override func_cloneType = this->get_override( "cloneType" ) )
            return func_cloneType(  );
        else{
            return this->osgSim::MultiSwitch::cloneType(  );
        }
    }
    
    ::osg::Object * default_cloneType(  ) const  {
        return osgSim::MultiSwitch::cloneType( );
    }

    virtual bool insertChild( unsigned int index, ::osg::Node * child ) {
        if( bp::override func_insertChild = this->get_override( "insertChild" ) )
            return func_insertChild( index, boost::python::ptr(child) );
        else{
            return this->osgSim::MultiSwitch::insertChild( index, boost::python::ptr(child) );
        }
    }
    
    bool default_insertChild( unsigned int index, ::osg::Node * child ) {
        return osgSim::MultiSwitch::insertChild( index, boost::python::ptr(child) );
    }

    virtual bool isSameKindAs( ::osg::Object const * obj ) const  {
        if( bp::override func_isSameKindAs = this->get_override( "isSameKindAs" ) )
            return func_isSameKindAs( boost::python::ptr(obj) );
        else{
            return this->osgSim::MultiSwitch::isSameKindAs( boost::python::ptr(obj) );
        }
    }
    
    bool default_isSameKindAs( ::osg::Object const * obj ) const  {
        return osgSim::MultiSwitch::isSameKindAs( boost::python::ptr(obj) );
    }

    virtual char const * libraryName(  ) const  {
        if( bp::override func_libraryName = this->get_override( "libraryName" ) )
            return func_libraryName(  );
        else{
            return this->osgSim::MultiSwitch::libraryName(  );
        }
    }
    
    char const * default_libraryName(  ) const  {
        return osgSim::MultiSwitch::libraryName( );
    }

    virtual bool removeChild( ::osg::Node * child ) {
        if( bp::override func_removeChild = this->get_override( "removeChild" ) )
            return func_removeChild( boost::python::ptr(child) );
        else{
            return this->osgSim::MultiSwitch::removeChild( boost::python::ptr(child) );
        }
    }
    
    bool default_removeChild( ::osg::Node * child ) {
        return osgSim::MultiSwitch::removeChild( boost::python::ptr(child) );
    }

    virtual void traverse( ::osg::NodeVisitor & nv ) {
        if( bp::override func_traverse = this->get_override( "traverse" ) )
            func_traverse( boost::ref(nv) );
        else{
            this->osgSim::MultiSwitch::traverse( boost::ref(nv) );
        }
    }
    
    void default_traverse( ::osg::NodeVisitor & nv ) {
        osgSim::MultiSwitch::traverse( boost::ref(nv) );
    }

    virtual ::osg::Camera * asCamera(  ) {
        if( bp::override func_asCamera = this->get_override( "asCamera" ) )
            return func_asCamera(  );
        else{
            return this->osg::Node::asCamera(  );
        }
    }
    
    ::osg::Camera * default_asCamera(  ) {
        return osg::Node::asCamera( );
    }

    virtual ::osg::Camera const * asCamera(  ) const  {
        if( bp::override func_asCamera = this->get_override( "asCamera" ) )
            return func_asCamera(  );
        else{
            return this->osg::Node::asCamera(  );
        }
    }
    
    ::osg::Camera const * default_asCamera(  ) const  {
        return osg::Node::asCamera( );
    }

    virtual ::osg::Geode * asGeode(  ) {
        if( bp::override func_asGeode = this->get_override( "asGeode" ) )
            return func_asGeode(  );
        else{
            return this->osg::Node::asGeode(  );
        }
    }
    
    ::osg::Geode * default_asGeode(  ) {
        return osg::Node::asGeode( );
    }

    virtual ::osg::Geode const * asGeode(  ) const  {
        if( bp::override func_asGeode = this->get_override( "asGeode" ) )
            return func_asGeode(  );
        else{
            return this->osg::Node::asGeode(  );
        }
    }
    
    ::osg::Geode const * default_asGeode(  ) const  {
        return osg::Node::asGeode( );
    }

    virtual ::osg::Group * asGroup(  ) {
        if( bp::override func_asGroup = this->get_override( "asGroup" ) )
            return func_asGroup(  );
        else{
            return this->osg::Group::asGroup(  );
        }
    }
    
    ::osg::Group * default_asGroup(  ) {
        return osg::Group::asGroup( );
    }

    virtual ::osg::Group const * asGroup(  ) const  {
        if( bp::override func_asGroup = this->get_override( "asGroup" ) )
            return func_asGroup(  );
        else{
            return this->osg::Group::asGroup(  );
        }
    }
    
    ::osg::Group const * default_asGroup(  ) const  {
        return osg::Group::asGroup( );
    }

    virtual ::osg::Switch * asSwitch(  ) {
        if( bp::override func_asSwitch = this->get_override( "asSwitch" ) )
            return func_asSwitch(  );
        else{
            return this->osg::Node::asSwitch(  );
        }
    }
    
    ::osg::Switch * default_asSwitch(  ) {
        return osg::Node::asSwitch( );
    }

    virtual ::osg::Switch const * asSwitch(  ) const  {
        if( bp::override func_asSwitch = this->get_override( "asSwitch" ) )
            return func_asSwitch(  );
        else{
            return this->osg::Node::asSwitch(  );
        }
    }
    
    ::osg::Switch const * default_asSwitch(  ) const  {
        return osg::Node::asSwitch( );
    }

    virtual ::osg::Transform * asTransform(  ) {
        if( bp::override func_asTransform = this->get_override( "asTransform" ) )
            return func_asTransform(  );
        else{
            return this->osg::Node::asTransform(  );
        }
    }
    
    ::osg::Transform * default_asTransform(  ) {
        return osg::Node::asTransform( );
    }

    virtual ::osg::Transform const * asTransform(  ) const  {
        if( bp::override func_asTransform = this->get_override( "asTransform" ) )
            return func_asTransform(  );
        else{
            return this->osg::Node::asTransform(  );
        }
    }
    
    ::osg::Transform const * default_asTransform(  ) const  {
        return osg::Node::asTransform( );
    }

    virtual void ascend( ::osg::NodeVisitor & nv ) {
        if( bp::override func_ascend = this->get_override( "ascend" ) )
            func_ascend( boost::ref(nv) );
        else{
            this->osg::Node::ascend( boost::ref(nv) );
        }
    }
    
    void default_ascend( ::osg::NodeVisitor & nv ) {
        osg::Node::ascend( boost::ref(nv) );
    }

    virtual ::osg::BoundingSphere computeBound(  ) const  {
        if( bp::override func_computeBound = this->get_override( "computeBound" ) )
            return func_computeBound(  );
        else{
            return this->osg::Group::computeBound(  );
        }
    }
    
    ::osg::BoundingSphere default_computeBound(  ) const  {
        return osg::Group::computeBound( );
    }

    virtual void computeDataVariance(  ) {
        if( bp::override func_computeDataVariance = this->get_override( "computeDataVariance" ) )
            func_computeDataVariance(  );
        else{
            this->osg::Object::computeDataVariance(  );
        }
    }
    
    void default_computeDataVariance(  ) {
        osg::Object::computeDataVariance( );
    }

    virtual ::osg::Referenced * getUserData(  ) {
        if( bp::override func_getUserData = this->get_override( "getUserData" ) )
            return func_getUserData(  );
        else{
            return this->osg::Object::getUserData(  );
        }
    }
    
    ::osg::Referenced * default_getUserData(  ) {
        return osg::Object::getUserData( );
    }

    virtual ::osg::Referenced const * getUserData(  ) const  {
        if( bp::override func_getUserData = this->get_override( "getUserData" ) )
            return func_getUserData(  );
        else{
            return this->osg::Object::getUserData(  );
        }
    }
    
    ::osg::Referenced const * default_getUserData(  ) const  {
        return osg::Object::getUserData( );
    }

    virtual bool removeChildren( unsigned int pos, unsigned int numChildrenToRemove ) {
        if( bp::override func_removeChildren = this->get_override( "removeChildren" ) )
            return func_removeChildren( pos, numChildrenToRemove );
        else{
            return this->osg::Group::removeChildren( pos, numChildrenToRemove );
        }
    }
    
    bool default_removeChildren( unsigned int pos, unsigned int numChildrenToRemove ) {
        return osg::Group::removeChildren( pos, numChildrenToRemove );
    }

    virtual bool replaceChild( ::osg::Node * origChild, ::osg::Node * newChild ) {
        if( bp::override func_replaceChild = this->get_override( "replaceChild" ) )
            return func_replaceChild( boost::python::ptr(origChild), boost::python::ptr(newChild) );
        else{
            return this->osg::Group::replaceChild( boost::python::ptr(origChild), boost::python::ptr(newChild) );
        }
    }
    
    bool default_replaceChild( ::osg::Node * origChild, ::osg::Node * newChild ) {
        return osg::Group::replaceChild( boost::python::ptr(origChild), boost::python::ptr(newChild) );
    }

    virtual void resizeGLObjectBuffers( unsigned int maxSize ) {
        if( bp::override func_resizeGLObjectBuffers = this->get_override( "resizeGLObjectBuffers" ) )
            func_resizeGLObjectBuffers( maxSize );
        else{
            this->osg::Group::resizeGLObjectBuffers( maxSize );
        }
    }
    
    void default_resizeGLObjectBuffers( unsigned int maxSize ) {
        osg::Group::resizeGLObjectBuffers( maxSize );
    }

    virtual bool setChild( unsigned int i, ::osg::Node * node ) {
        if( bp::override func_setChild = this->get_override( "setChild" ) )
            return func_setChild( i, boost::python::ptr(node) );
        else{
            return this->osg::Group::setChild( i, boost::python::ptr(node) );
        }
    }
    
    bool default_setChild( unsigned int i, ::osg::Node * node ) {
        return osg::Group::setChild( i, boost::python::ptr(node) );
    }

    virtual void setName( ::std::string const & name ) {
        if( bp::override func_setName = this->get_override( "setName" ) )
            func_setName( name );
        else{
            this->osg::Object::setName( name );
        }
    }
    
    void default_setName( ::std::string const & name ) {
        osg::Object::setName( name );
    }

    virtual void setThreadSafeRefUnref( bool threadSafe ) {
        if( bp::override func_setThreadSafeRefUnref = this->get_override( "setThreadSafeRefUnref" ) )
            func_setThreadSafeRefUnref( threadSafe );
        else{
            this->osg::Group::setThreadSafeRefUnref( threadSafe );
        }
    }
    
    void default_setThreadSafeRefUnref( bool threadSafe ) {
        osg::Group::setThreadSafeRefUnref( threadSafe );
    }

    virtual void setUserData( ::osg::Referenced * obj ) {
        if( bp::override func_setUserData = this->get_override( "setUserData" ) )
            func_setUserData( boost::python::ptr(obj) );
        else{
            this->osg::Object::setUserData( boost::python::ptr(obj) );
        }
    }
    
    void default_setUserData( ::osg::Referenced * obj ) {
        osg::Object::setUserData( boost::python::ptr(obj) );
    }

};

void register_MultiSwitch_class(){

    bp::class_< MultiSwitch_wrapper, bp::bases< ::osg::Group >, osg::ref_ptr< MultiSwitch_wrapper >, boost::noncopyable >( "MultiSwitch", "\n MultiSwitch is a Group node which allows switching between sets of selected children.\n    MultiSwitch is based on the OpenFlight switch behaviour.\n", bp::no_init )    
        .def( bp::init< >("\n MultiSwitch is a Group node which allows switching between sets of selected children.\n    MultiSwitch is based on the OpenFlight switch behaviour.\n") )    
        .def( 
            "accept"
            , (void ( ::osgSim::MultiSwitch::* )( ::osg::NodeVisitor & ))(&::osgSim::MultiSwitch::accept)
            , (void ( MultiSwitch_wrapper::* )( ::osg::NodeVisitor & ))(&MultiSwitch_wrapper::default_accept)
            , ( bp::arg("nv") ) )    
        .def( 
            "addChild"
            , (bool ( ::osgSim::MultiSwitch::* )( ::osg::Node * ))(&::osgSim::MultiSwitch::addChild)
            , (bool ( MultiSwitch_wrapper::* )( ::osg::Node * ))(&MultiSwitch_wrapper::default_addChild)
            , ( bp::arg("child") ) )    
        .def( 
            "className"
            , (char const * ( ::osgSim::MultiSwitch::* )(  )const)(&::osgSim::MultiSwitch::className)
            , (char const * ( MultiSwitch_wrapper::* )(  )const)(&MultiSwitch_wrapper::default_className) )    
        .def( 
            "clone"
            , (::osg::Object * ( ::osgSim::MultiSwitch::* )( ::osg::CopyOp const & )const)(&::osgSim::MultiSwitch::clone)
            , (::osg::Object * ( MultiSwitch_wrapper::* )( ::osg::CopyOp const & )const)(&MultiSwitch_wrapper::default_clone)
            , ( bp::arg("copyop") )
            , bp::return_value_policy< bp::reference_existing_object >() )    
        .def( 
            "cloneType"
            , (::osg::Object * ( ::osgSim::MultiSwitch::* )(  )const)(&::osgSim::MultiSwitch::cloneType)
            , (::osg::Object * ( MultiSwitch_wrapper::* )(  )const)(&MultiSwitch_wrapper::default_cloneType)
            , bp::return_value_policy< bp::reference_existing_object >() )    
        .def( 
            "getActiveSwitchSet"
            , (unsigned int ( ::osgSim::MultiSwitch::* )(  )const)( &::osgSim::MultiSwitch::getActiveSwitchSet )
            , " Get which of the available switch set lists to use." )    
        .def( 
            "getChildValue"
            , (bool ( ::osgSim::MultiSwitch::* )( ::osg::Node const *,unsigned int )const)( &::osgSim::MultiSwitch::getChildValue )
            , ( bp::arg("child"), bp::arg("switchSet") ) )    
        .def( 
            "getNewChildDefaultValue"
            , (bool ( ::osgSim::MultiSwitch::* )(  )const)( &::osgSim::MultiSwitch::getNewChildDefaultValue ) )    
        .def( 
            "getValue"
            , (bool ( ::osgSim::MultiSwitch::* )( unsigned int,unsigned int )const)( &::osgSim::MultiSwitch::getValue )
            , ( bp::arg("switchSet"), bp::arg("pos") ) )    
        .def( 
            "getValueName"
            , (::std::string const & ( ::osgSim::MultiSwitch::* )( unsigned int )const)( &::osgSim::MultiSwitch::getValueName )
            , ( bp::arg("switchSet") )
            , bp::return_value_policy< bp::copy_const_reference >() )    
        .def( 
            "insertChild"
            , (bool ( ::osgSim::MultiSwitch::* )( unsigned int,::osg::Node * ))(&::osgSim::MultiSwitch::insertChild)
            , (bool ( MultiSwitch_wrapper::* )( unsigned int,::osg::Node * ))(&MultiSwitch_wrapper::default_insertChild)
            , ( bp::arg("index"), bp::arg("child") ) )    
        .def( 
            "isSameKindAs"
            , (bool ( ::osgSim::MultiSwitch::* )( ::osg::Object const * )const)(&::osgSim::MultiSwitch::isSameKindAs)
            , (bool ( MultiSwitch_wrapper::* )( ::osg::Object const * )const)(&MultiSwitch_wrapper::default_isSameKindAs)
            , ( bp::arg("obj") ) )    
        .def( 
            "libraryName"
            , (char const * ( ::osgSim::MultiSwitch::* )(  )const)(&::osgSim::MultiSwitch::libraryName)
            , (char const * ( MultiSwitch_wrapper::* )(  )const)(&MultiSwitch_wrapper::default_libraryName) )    
        .def( 
            "removeChild"
            , (bool ( ::osgSim::MultiSwitch::* )( ::osg::Node * ))(&::osgSim::MultiSwitch::removeChild)
            , (bool ( MultiSwitch_wrapper::* )( ::osg::Node * ))(&MultiSwitch_wrapper::default_removeChild)
            , ( bp::arg("child") ) )    
        .def( 
            "setActiveSwitchSet"
            , (void ( ::osgSim::MultiSwitch::* )( unsigned int ))( &::osgSim::MultiSwitch::setActiveSwitchSet )
            , ( bp::arg("switchSet") )
            , " Set which of the available switch set lists to use." )    
        .def( 
            "setAllChildrenOff"
            , (bool ( ::osgSim::MultiSwitch::* )( unsigned int ))( &::osgSim::MultiSwitch::setAllChildrenOff )
            , ( bp::arg("switchSet") )
            , " Set all the children off (false), and set the new default child value to off (false)." )    
        .def( 
            "setAllChildrenOn"
            , (bool ( ::osgSim::MultiSwitch::* )( unsigned int ))( &::osgSim::MultiSwitch::setAllChildrenOn )
            , ( bp::arg("switchSet") )
            , " Set all the children on (true), and set the new default child value to on (true)." )    
        .def( 
            "setChildValue"
            , (void ( ::osgSim::MultiSwitch::* )( ::osg::Node const *,unsigned int,bool ))( &::osgSim::MultiSwitch::setChildValue )
            , ( bp::arg("child"), bp::arg("switchSet"), bp::arg("value") ) )    
        .def( 
            "setNewChildDefaultValue"
            , (void ( ::osgSim::MultiSwitch::* )( bool ))( &::osgSim::MultiSwitch::setNewChildDefaultValue )
            , ( bp::arg("value") ) )    
        .def( 
            "setSingleChildOn"
            , (bool ( ::osgSim::MultiSwitch::* )( unsigned int,unsigned int ))( &::osgSim::MultiSwitch::setSingleChildOn )
            , ( bp::arg("switchSet"), bp::arg("pos") )
            , " Set a single child to be on, MultiSwitch off all other children." )    
        .def( 
            "setValue"
            , (void ( ::osgSim::MultiSwitch::* )( unsigned int,unsigned int,bool ))( &::osgSim::MultiSwitch::setValue )
            , ( bp::arg("switchSet"), bp::arg("pos"), bp::arg("value") ) )    
        .def( 
            "setValueName"
            , (void ( ::osgSim::MultiSwitch::* )( unsigned int,::std::string const & ))( &::osgSim::MultiSwitch::setValueName )
            , ( bp::arg("switchSet"), bp::arg("name") ) )    
        .def( 
            "traverse"
            , (void ( ::osgSim::MultiSwitch::* )( ::osg::NodeVisitor & ))(&::osgSim::MultiSwitch::traverse)
            , (void ( MultiSwitch_wrapper::* )( ::osg::NodeVisitor & ))(&MultiSwitch_wrapper::default_traverse)
            , ( bp::arg("nv") ) );

}
